---
abstract: "Path-like config API with multiple file support, directory\nloading and arbitrary backends from Config::Any."
author:
  - 'Cory G Watson <gphat@cpan.org>'
build_requires:
  Data::Dumper: 0
  Test::Exception: 0
  Test::More: 0
  XML::Simple: 0
  strict: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300010, CPAN::Meta::Converter version 2.120630'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Config-Path
requires:
  Config::Any: 0
  Hash::Merge: 0
  JSON::Any: 0
  JSON::XS: 0
  Moose: 0
resources:
  bugtracker: https://github.com/magazinesdotcom/config-path/issues
  homepage: https://github.com/magazinesdotcom/config-path
  repository: https://github.com/magazinesdotcom/config-path.git
version: 0.13
